---
jobs:
  - job: tests
    trigger: pull_request
    branch: main
    targets:
      - fedora-rawhide
    skip_build: true
    tf_extra_params:
      environments:
        - tmt:
            context:
              target_PR_branch: main
              OC: "false"
              UPSTREAM_CODE: "false"
  - job: tests
    trigger: pull_request
    identifier: image_upstream_code
    branch: main
    targets:
      - fedora-stable
    skip_build: true
    tf_extra_params:
      environments:
        - tmt:
            context:
              target_PR_branch: main
              OC: "false"
